sign_in_button_home_page = "xpath = //a[contains(@class,'login')]"
email_field = "xpath = //input[@id='email_create']"
create_account_button = "xpath = //button[@id='SubmitCreate']"
first_name = "xpath = //input[@id='customer_firstname']"
your_personal_information = "xpath=//h3[@class='page-subheading']"
last_name = "xpath = //input[@id='customer_lastname']"
password = "xpath = //input[@id='passwd']"
address = "xpath = //input[@id='address1']"
city = "xpath = //input[@id='city']"
state = "xpath = //select[@id='id_state']"
postal_code = "xpath = //input[@id='postcode']"
mobile_phone = "xpath = //input[@id='phone_mobile']"
assign_address = "xpath = //input[@id='alias']"
register_button = "xpath = //button[@id='submitAccount']"
